# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cartsdb:
  enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi

carts:
  enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 200Mi
    requests:
      cpu: 300m
      memory: 200Mi