apiVersion: v1
kind: Service
metadata:
  name: {{ include "carts-db.fullname" . }}
  labels:
    {{- include "carts-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "carts-db.selectorLabels" . | nindent 4 }}
