apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sock-shop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - sock-shop.testruction.io
      secretName: sock-shop-general-cert
  rules:
    - host: sock-shop.testruction.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
